### ISSUE TITLE
[BUG] Potential infinite recursion on `repr(treespec)` / `hash(treespec)` when the node metadata references the `treespec` itself

### ISSUE THREAD

**Issue by XuehaiPan** [metaopt/optree#81]
### Required prerequisites

- [X] I have read the documentation <https://optree.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/metaopt/optree/issues) that this hasn't already been reported. (comment there if it has.)

### What version of OpTree are you using?

0.9.2

### System information

- Install from source
- Python version: 3.11.5

### Problem description

The `treespec` representation calls `repr` / `hash` for the node metadata for each node. When the node metadata references the `treespec` itself, this will cause infinite recursion of calling `repr(treespec)` / `hash(treespec)`.

Note that this situation is almost impossible to happen in the real world.

### Reproducible example code

The Python snippets:

```python
import optree


class Holder:
    def __init__(self, value):
        self.value = value

    def __eq__(self, other):
        return isinstance(other, Holder) and self.value == other.value

    def __hash__(self):
        return hash(self.value)

    def __repr__(self):
        return f'Holder({self.value!r})'


key = Holder('a')

treespec = optree.tree_structure({key: 0})
print(treespec)  # -> PyTreeSpec({Holder('a'): *})

key.value = 'b'
print(treespec)  # -> PyTreeSpec({Holder('b'): *})

key.value = treespec  # self reference
print(treespec)  # -> RecursionError
print(hash(treespec))  # -> RecursionError
```

### Traceback

```pytb
Traceback (most recent call last):
  File "/Users/PanXuehai/Projects/optree/test.py", line 27, in <module>
    print(treespec)  # -> RecursionError
    ^^^^^^^^^^^^^^^
  File "/Users/PanXuehai/Projects/optree/test.py", line 15, in __repr__
    return f'Holder({self.value!r})'
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/PanXuehai/Projects/optree/test.py", line 15, in __repr__
    return f'Holder({self.value!r})'
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/PanXuehai/Projects/optree/test.py", line 15, in __repr__
    return f'Holder({self.value!r})'
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 246 more times]
RecursionError: maximum recursion depth exceeded while getting the repr of an object

Traceback (most recent call last):
  File "/Users/PanXuehai/Projects/optree/test.py", line 27, in <module>
    print(hash(treespec))  # -> RecursionError
          ^^^^^^^^^^^^^^
  File "/Users/PanXuehai/Projects/optree/test.py", line 12, in __hash__
    return hash(self.value)
           ^^^^^^^^^^^^^^^^
  File "/Users/PanXuehai/Projects/optree/test.py", line 12, in __hash__
    return hash(self.value)
           ^^^^^^^^^^^^^^^^
  File "/Users/PanXuehai/Projects/optree/test.py", line 12, in __hash__
    return hash(self.value)
           ^^^^^^^^^^^^^^^^
  [Previous line repeated 330 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by XuehaiPan** [comment]
Opened a discussion on the Python Forum:

- [Add recursion guard for `hash()` function like `repr.recursive_repr()` to avoid infinite recursion](https://discuss.python.org/t/add-recursion-guard-for-hash-function-like-repr-recursive-repr-to-avoid-infinite-recursion/34521/1)
